#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FMSKeygen_Android.Resource", IsApplication=true)]

namespace FMSKeygen_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::FMSKeygen_Android.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::FMSKeygen_Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::FMSKeygen_Android.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000a
			public const int btnClear = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int btnCopy = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int btnGetActiviationCode = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int btnReadQRCode = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int btnScanQRCode = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int btnShare = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int contentFrame = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int gridLayout1 = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int tvActiviationCode = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int tvMachineCode = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int txtActiviationCode = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int txtMachineCode = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int zxingscanneractivitylayout = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int zxingscannerfragmentlayout = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
